language: cpp
compiler:
  - gcc
#  - clang
sudo: required
dist: trusty

install:
  # CppCheck
  - sudo apt-get install -qq cppcheck
  # Gcovr
  - sudo apt-get install gcovr
  # Pybind11
  - sudo apt-get install python3-pip
  - sudo python3 -m pip install pybind11

script:
  # Runs compilation, cppcheck, tests and coverage collection
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_CODECOV=ON -DENABLE_TESTS=ON -DENABLE_CPPCHECK=ON
  - make && make "TEST_FLAGS=-D__linux__" cppcheck && (make coverage || (cat ./Testing/Temporary/LastTest.log && exit 1))
  - cd ..

after_success:
    # codecov.io
    #- bash <(curl -s https://codecov.io/bash) -X gcov -f 'test/gcov/*.gcov'
    - bash <(curl -s https://codecov.io/bash) -X gcov -f build/coverage.xml

notifications:
  email:
    recipients:
      - d.desensi.software@gmail.com
    on_success: never # default: change
    on_failure: always # default: always